version: 0.1

phases:
  install:  
    commands:
      - echo installing nodejs ...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash - 
      - apt-get install -y nodejs
      - echo installing yarn ...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      -
      -
      -
      -

  pre_build:
    commands:
      - echo installing dependencies
      - npm install
  build:
    commands:
      - echo building ...
      - npm run build

artifacts:
  files: 
    - "**/*"
  discard-paths: no
  base_directory: build
